### ISSUE TITLE
Regular shutdown of OCP5 Control nodes hung

### ISSUE THREAD

**Issue by stefan-bergstein** [stormshift/support#104]
Shutdown of worker nodes worked fine:
```
for node in inf45.coe.muc.redhat.com inf49.coe.muc.redhat.com; do oc debug node/${node} -- chroot /host shutdown -h 1; done
```
Shutdown of control nodes:
```
for node in ocp5-control-0 ocp5-control-1 ocp5-control-2; do oc debug node/${node} -- chroot /host shutdown -h 1; done
```

... cp5-control-1 hung for 10 minutes:

![OPC5-Control1-Screenshot](https://user-images.githubusercontent.com/19570494/187878991-914082b4-9c87-4c86-b1b8-2e04bbf791e1.png)

Note, control nodes host ODF with PCI passthrough disks and pinned nodes.

Workaround: Force stop VM via RHV connsole.

**Comment by rbo** [comment]
Close... to old.
