### ISSUE TITLE
Reinstall Satellite at inf3

### ISSUE THREAD

**Issue by rbo** [stormshift/support#112]
- [x] Move dhcpd inclusive configuration and leases to inf1=> @rbo
- [x] Check Managment Board & Remote Access at inf3 => @rbo 
- [x] Reinstall inf3 with latest RHEL8 => @tux1980 ?
- [x] Install Satellite at inf3
- [ ] Connect Satellite to OpenShift Virt Cluster => api.cluster.coe....

**Comment by tux1980** [comment]
Confirming the ToDo's as of "Reinstall inf3 with latest RHEL8"

**Comment by rbo** [comment]
DHCPd migration scheduled for Monday 2022-12-12 11-12 CET 
COE & Storm chat informed.

On Monday 2022-12-12 11:00 CET I plan to migrate the dhcpd from inf3 to inf31 including the configuration and leases.  Please let me know any objections.
https://github.com/stormshift/support/issues/112

**Comment by rbo** [comment]
Target host changed from inf31 to inf1 because dhcpd will stay in inf1 and not migrated back on Satellite host.

Start migration and update && reboot of inf1

**Comment by rbo** [comment]
@tux1980 inf3 is reinstalled:
```
$ ssh -l root inf3.coe.muc.redhat.com
Warning: Permanently added 'inf3.coe.muc.redhat.com' (ED25519) to the list of known hosts.
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Thu Dec 15 11:57:52 2022 from 10.22.8.185
[root@inf3 ~]# lsblk 
NAME               MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                  8:0    0 683.5G  0 disk 
├─sda1               8:1    0     1G  0 part /boot
└─sda2               8:2    0   624G  0 part 
  ├─rhel_inf3-root 253:0    0    70G  0 lvm  /
  ├─rhel_inf3-swap 253:1    0     4G  0 lvm  [SWAP]
  ├─rhel_inf3-home 253:2    0    50G  0 lvm  /home
  └─rhel_inf3-var  253:3    0   500G  0 lvm  /var
sr0                 11:0    1  1024M  0 rom  
[root@inf3 ~]# df -h
Filesystem                  Size  Used Avail Use% Mounted on
devtmpfs                     48G     0   48G   0% /dev
tmpfs                        48G     0   48G   0% /dev/shm
tmpfs                        48G  9.4M   48G   1% /run
tmpfs                        48G     0   48G   0% /sys/fs/cgroup
/dev/mapper/rhel_inf3-root   70G  2.0G   68G   3% /
/dev/sda1                  1007M  216M  792M  22% /boot
/dev/mapper/rhel_inf3-home   50G  390M   50G   1% /home
/dev/mapper/rhel_inf3-var   500G  3.7G  497G   1% /var
tmpfs                       9.5G     0  9.5G   0% /run/user/0
[root@inf3 ~]# subscription-manager status
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Unknown

System Purpose Status: Unknown

[root@inf3 ~]# 
```

**Comment by tux1980** [comment]
Thanks. perfect. Will start the Sat 6.12.0 Installation next week around wed, thu.....

**Comment by tux1980** [comment]
Hi guys,

the satellite 6.12 Server has been installed today. You can find the Credentials for the Admin User and URL here (In the old Lab Docu in Page 2):
https://docs.google.com/document/d/1drXU7dLSt4-JJjaHSCIT8RzkL4Ss_xy1kwFhDBN0V8Q/edit# 

Be aware: I created the "Organization" coe and "Location "Technik" with an initial Manifest. this Org is only thougt of to manage infra service in our CoE. Please create your own Organization and Manifest.

**Comment by rbo** [comment]
inf3 is destroyed and in use for other topics. We can close the issue. Looks like nobody really miss the Satellite.
