### ISSUE TITLE
storm3 - memory error

### ISSUE THREAD

**Issue by rbo** [stormshift/support#115]
![image](https://user-images.githubusercontent.com/36604/208307372-7810d906-398e-4ed9-88d3-d830355a8d3f.png)

**Comment by rbo** [comment]
<div class="table_title" id="indivMemoryTitle">Individual Memory Details</div>
                    

  | Status | Connector Name | Type | Size | State | Rank | Speed |  
-- | -- | -- | -- | -- | -- | -- | -- | --
  |   | DIMM A4 | DDR-4 | 32.00 GB | Uncorrectable Memory Error | Dual Rank | 1866 MHz |  
  |   | DIMM B11 | DDR-4 | 32.00 GB | Uncorrectable Memory Error | Dual Rank | 1866 MHz

Two DIMM's show an error

**Comment by rbo** [comment]
![image](https://user-images.githubusercontent.com/36604/208307768-c28a7fbc-2f76-4fe5-9c49-4be637b45a53.png)

These DIMM's looks broken.

**Comment by rbo** [comment]
According to https://dl.dell.com/topicspdf/poweredge-r730_owners-manual2_en-us.pdf page 80

**Comment by rbo** [comment]
I can switch DIMM's for example B11 <> B4, and A4 <> A8 if the error move from B11 to B4 and A4 and A8 the dimm are really broken. 

**DIMM Modules in the Server**
<span class="font-weight-medium text-jet pr-4">370-ABVW : 32GB RDIMM, 2.133MT/s, Dual Rank, x4 Datenbreite</span>
                
Teilenummer | Beschreibung | Menge
-- | -- | --
PR5D1 | DIMM,32GB,2133,2RX4,8G,DDR4,R | 24

**Comment by rbo** [comment]
DIMM's switched: B11 <> B4 and A4 <> A8 

![image](https://user-images.githubusercontent.com/36604/208661960-a1e09457-a6e0-49fe-8067-8f62bd8e7387.png)

Right now, no errors in iDRAC.

@DanielFroehlich  is running several memtests.

**Comment by DanielFroehlich** [comment]
lgtm meanwhile
