### ISSUE TITLE
Add MicroShift to deployment automation

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#127]
Provision a new VM with MicroShift
Add DNS entries to DHCP ID for easy external access
Optionally: add to ACM
Use similiar cfg scheme as with ocp

**Comment by stefan-bergstein** [comment]
1. I would like to offer help for testing.
2. These playbooks might help with implementation: https://github.com/stormshift/automation/tree/master/assisted-installer

**Comment by DanielFroehlich** [comment]
simple rpm based ushift is done.
