### ISSUE TITLE
Consider new Root CA Cert

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#129]
With the next server cert rotation, we need to switch to the new Red Hat Internal CA Root CA Cert.
See https://source.redhat.com/groups/public/identity-access-management/rhcs_red_hat_certificate_system_wiki/announcement_action_required_2023_new_red_hat_corporate_root_certificate

**Comment by rbo** [comment]
Feel free to checkout and use : https://gitlab.consulting.redhat.com/coe-lab/certificates

Ah private central store or all certs and some "tooling"

**Comment by DanielFroehlich** [comment]
added new Root CA Cert on last cert rotation in Jan/2024
