### ISSUE TITLE
Enable Observability at ACM

### ISSUE THREAD

**Issue by rbo** [stormshift/support#135]

**Comment by DanielFroehlich** [comment]
I will do this if you dont mind - this is kind of the last missing piece to get feature/demo parity with stormshift ACM, and its not that hard. now that I got the hang of gitops....

**Comment by DanielFroehlich** [comment]
@rbo : I did enable ACM observability test wise tonight (gitops PR is coming soon, I jus manually applied).

Per default, all managed clusters are observed.  I could imagine that this has a hefty resource impact on both the hub and spoke clusters. If that is too much, we can disable for single clusters, or (in kind of emergencies) completely quite easily.
See here:
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.10/html-single/observability/index#disabling-observability

**Comment by DanielFroehlich** [comment]
Pull Secret warnings need to be fixed:
`Unable to retrieve some image pull secrets (multiclusterhub-operator-pull-secret); attempting to pull the image may not succeed.
`

**Comment by DanielFroehlich** [comment]
Implementation is part of https://github.com/stormshift/clusters/pull/13

**Comment by DanielFroehlich** [comment]
Done! Works also via gitops!
Key elements are:

1. - https://github.com/stormshift/clusters/blob/main/isar-apps/acm/MultiClusterObservability/observability.yaml
2. - https://github.com/stormshift/clusters/blob/main/isar-apps/acm/ExternalSecret/thanos-object-storage.yaml
3. - https://github.com/stormshift/clusters/blob/main/isar-apps/acm/ObjectBucketClaim/acm-observability-thanos-bucket.yaml

This is not 100% gitops, as the thanos-object-storage external secret needs to contain value in the vault that are genereated from the ObjectBucketClaim.
Need to find a better way to point to that source. But works for now.
