### ISSUE TITLE
storm6 failed ssd

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#137]
Storm6 shows failed SSD, the OS raid cluster has loss of redundancy, we might lose storm6 any time.
The mmgt cluster (Acm / acs) has storage tied to storm6 nfs server.

Disk in slot #3 is the culprit:
![image](https://github.com/stormshift/support/assets/18532443/bde904ef-7c89-4df1-9021-210699f6ff61)

Failed disk is of type:
![image](https://github.com/stormshift/support/assets/18532443/18855769-451d-43ab-9f3b-119c621b0597)

**Comment by rbo** [comment]
* https://www.kimbrer.de/dell-r3j3y.html?gad=1&gclid=EAIaIQobChMI-Z2Fsv7g_wIVF1dyCh2nNAIKEAQYASABEgJhW_D_BwE
  => 224 Euro

**Comment by rbo** [comment]
Disk orderd: Bestellung # KIM023952

**Comment by rbo** [comment]
The disk should arrive on Thursday, I'm in the office on Friday and will replace the disk. 

@DanielFroehlich can you manage the "recovery"?

**Comment by DanielFroehlich** [comment]
Thanks a lot for getting the spare! I have no clue what needs to be done, but I will find out and manage it.
Do you need the node to be down, or is this hot pluggable?

**Comment by rbo** [comment]
It should be hot pluggable. I will check in iDrac before "plugging" around :-D

**Comment by rbo** [comment]
Disks replaced, virtual disk rebuilt. All green!
