### ISSUE TITLE
OCP4 Compute 0 stuck with 0% CPU

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#145]
Processes cannot be started, waiting forever. Shutdown and reboot does not help. VM runs on storm3.

**Comment by Javatar81** [comment]
[core@compute-0 ~]$ sudo systemctl status kubelet
○ kubelet.service - Kubernetes Kubelet
     Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─01-kubens.conf, 10-mco-default-madv.conf, 20-logging.conf, 20-nodenet.conf
     Active: inactive (dead)

journalctl -b -u kubelet.service -u crio.service
-- No entries --

sudo systemctl start kubelet 
--- WAITING FOREVER ----

**Comment by Javatar81** [comment]
Oct 27 09:09:25 compute-0.ocp4.stormshift.coe.muc.redhat.com bash[21212]: Error: readlink /var/lib/containers/storage/overlay: invalid argument
Oct 27 09:09:25 compute-0.ocp4.stormshift.coe.muc.redhat.com systemd[1]: var-lib-containers-storage-overlay.mount: Deactivated successfully.

**Comment by rbo** [comment]
Just deleted the notready node 
```
$ oc delete node compute-0.ocp4.stormshift.coe.muc.redhat.com
node "compute-0.ocp4.stormshift.coe.muc.redhat.com" deleted
```

To get MCO & ready again

**Comment by rbo** [comment]
Hard reboot of node `compute-0.ocp4.stormshift.coe.muc.redhat.com`

**Comment by Javatar81** [comment]
Scheduling is disabled for compute-0. Can I schedule or are you still working on this?

**Comment by rbo** [comment]
I'm working on it

**Comment by rbo** [comment]
Compute-0 joining again, csr apprioved.
```
compute-0.ocp4.stormshift.coe.muc.redhat.com   NotReady                   worker          1s       v1.26.9+c7606e7

```

**Comment by rbo** [comment]
Solution was to cleanup all images: `sudo podman rmi --all`

**Comment by rbo** [comment]
Looks like cluster is working again.
