### ISSUE TITLE
Install Red Hat Certificates to IPA servers inf1/inf31

### ISSUE THREAD

**Issue by rbo** [stormshift/support#155]

**Comment by rbo** [comment]
Problem with IPA directory manager password.
```bash
[root@inf1 cert]# ipa-server-certinstall -w wildcard-coe.enc.key wildcard-coe.chain.cert 
Directory Manager password: 

Enter private key unlock password: 

Insufficient access:  Invalid credentials
The ipa-server-certinstall command failed.
```

Tried numerous passwords via: `[root@inf1 cert]# ldapsearch -x uid=rbohne -D 'cn=Directory Manager -W`

Find the right one... Document in bitwarden.

**Comment by rbo** [comment]
Certificates stored here: https://gitlab.consulting.redhat.com/coe-lab/certificates

**Comment by rbo** [comment]
```bash
[root@inf1 cert]# ipa-server-certinstall  -w wildcard-coe.enc.key wildcard-coe.full-chain.cert 
Directory Manager password: 

Enter private key unlock password: 

Please restart ipa services after installing certificate (ipactl restart)
The ipa-server-certinstall command was successful
[root@inf1 cert]# ipactl restart
Restarting Directory Service
Restarting krb5kdc Service
Restarting kadmin Service
Restarting named Service
Restarting httpd Service
Restarting ipa-custodia Service
Restarting pki-tomcatd Service
Restarting ipa-otpd Service
Restarting ipa-dnskeysyncd Service
ipa: INFO: The ipactl command was successful
[root@inf1 cert]# 
```

**Comment by rbo** [comment]
Problem: Webserver don't deliver intermediate certificate.

**Comment by rbo** [comment]
Install Red Hat Root & Intermediate:
```bash
[root@inf1 cert]# ipa-cacert-manage install root.cert 
Installing CA certificate, please wait
Verified E=infosec@redhat.com,CN=Internal Root CA,OU=Red Hat IT,O=Red Hat\, Inc.,L=Raleigh,ST=North Carolina,C=US
CA certificate successfully installed
The ipa-cacert-manage command was successful
[root@inf1 cert]# ipa-cacert-manage install intermediate.cert 
Installing CA certificate, please wait
Verified CN=2023 Certificate Authority RHCSv2,OU=prod,O=Red Hat
CA certificate successfully installed
The ipa-cacert-manage command was successful
[root@inf1 cert]# ipa-cacert-manage list
COE.MUC.REDHAT.COM IPA CA
E=infosec@redhat.com,CN=Internal Root CA,OU=Red Hat IT,O=Red Hat\, Inc.,L=Raleigh,ST=North Carolina,C=US
CN=2023 Certificate Authority RHCSv2,OU=prod,O=Red Hat
The ipa-cacert-manage command was successful
[root@inf1 cert]# ipa-certupdate
Connection to https://inf1.coe.muc.redhat.com/ipa/json failed with [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)
Systemwide CA database updated.
The ipa-certupdate command was successful
[root@inf1 cert]# 
```

**Comment by rbo** [comment]
Replication to inf31 works for cacert as well:
```
[root@inf31 ~]# ipa-cacert-manage list
COE.MUC.REDHAT.COM IPA CA
E=infosec@redhat.com,CN=Internal Root CA,OU=Red Hat IT,O=Red Hat\, Inc.,L=Raleigh,ST=North Carolina,C=US
CN=2023 Certificate Authority RHCSv2,OU=prod,O=Red Hat
The ipa-cacert-manage command was successful
```

**Comment by rbo** [comment]
Take sure:
```bash
[root@inf31 ~]#  ipa-certupdate
Systemwide CA database updated.
Systemwide CA database updated.
The ipa-certupdate command was successful
[root@inf31 ~]# 
```

**Comment by rbo** [comment]
```
[root@inf31 cert]# ipa-server-certinstall  -w wildcard-coe.enc.key wildcard-coe.chain.cert
Directory Manager password: 

Enter private key unlock password: 

Please restart ipa services after installing certificate (ipactl restart)
The ipa-server-certinstall command was successful
[root@inf31 cert]# ipactl restart
Restarting Directory Service
Restarting krb5kdc Service
Restarting kadmin Service
Restarting named Service
Restarting httpd Service
Restarting ipa-custodia Service
Restarting pki-tomcatd Service
Restarting ipa-otpd Service
Restarting ipa-dnskeysyncd Service
ipa: INFO: The ipactl command was successful
[root@inf31 cert]# 
```

Replication tested as well. DONE!

**Comment by mimamidada** [comment]
> Problem with IPA directory manager password.
> 
> ```shell
> [root@inf1 cert]# ipa-server-certinstall -w wildcard-coe.enc.key wildcard-coe.chain.cert 
> Directory Manager password: 
> 
> Enter private key unlock password: 
> 
> Insufficient access:  Invalid credentials
> The ipa-server-certinstall command failed.
> ```
> 
> Tried numerous passwords via: `[root@inf1 cert]# ldapsearch -x uid=rbohne -D 'cn=Directory Manager -W`
> 
> Find the right one... Document in bitwarden.

I have this problem, Directory Manager Password is always wrong, but i never change the password. i can login use kinit admin with the password, but can't use it for certinstall. Can you help me find the right one?

**Comment by rbo** [comment]
> > Problem with IPA directory manager password.
> > ```shell
> > [root@inf1 cert]# ipa-server-certinstall -w wildcard-coe.enc.key wildcard-coe.chain.cert 
> > Directory Manager password: 
> > 
> > Enter private key unlock password: 
> > 
> > Insufficient access:  Invalid credentials
> > The ipa-server-certinstall command failed.
> > ```
> > Tried numerous passwords via: `[root@inf1 cert]# ldapsearch -x uid=rbohne -D 'cn=Directory Manager -W`
> > Find the right one... Document in bitwarden.
> 
> I have this problem, Directory Manager Password is always wrong, but i never change the password. i can login use kinit admin with the password, but can't use it for certinstall. Can you help me find the right one?

@mimamidada Nope sorry, I'm not an IPA expert. It was just luck to find the right one.
