### ISSUE TITLE
keycloak operator deployed twice on isar?

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#161]
Did I have too much beer or am I seeing double?
![image](https://github.com/stormshift/support/assets/18532443/e671bd36-23a1-4db7-819d-1a2aa0b97b5e)

Looks like only rhbk-operator is in use , and infra-sso is obsolete?

**Comment by rbo** [comment]
No, my fault... 

I cleaned it. 

My plan was to install the sso into infra-sso namespace. But I messed it up.
