### ISSUE TITLE
ISAR Netapp Storage snapshot not working / Including Trident Update

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#167]
Snapshots not working due to no VolumeSnapshotClases
Would be nice to have that for quick VM cloning via smart snapshots.

**Comment by rbo** [comment]
First we update trident version from v23.01.0 to v24.02.0

```bash
$ oc get tridentversion -n netapp-trident
NAME      VERSION
trident   23.01.0
```

https://github.com/NetApp/trident/releases

**Comment by rbo** [comment]
Update:
```
cd github.com/stormshift/clusters/configuration/overlays/isar/namespace/netapp-trident
mkdir 24.02.0
cd 24.02.0
curl -L -O https://github.com/NetApp/trident/releases/download/v24.02.0/trident-installer-24.02.0.tar.gz
tar xzf trident-installer-24.02.0.tar.gz
mv trident-installer/deploy/* .
rm -rf trident-installer/ trident-installer-24.02.0.tar.gz 
...
```

```bash
oc get tridentversion -n netapp-trident
NAME      VERSION
trident   24.02.0
```

✅ Update done!

**Comment by rbo** [comment]
* NFS: Use ontap-nas when you have a max of a few hundred PVCs. Otherwise need to discuss about nas-eco, which does not support CSI snaps/clones (but can still be backed up with Astra Control).
* iSCSI: Use san-eco. Full support for CSI snaps/clones, scales well.
* Flexgroup: Only use if you need a PVC >100TB, e.g. never ;-)

**Comment by rbo** [comment]
Currently on use:

- [ontap-nas](https://github.com/stormshift/clusters/blob/main/configuration/overlays/isar/namespace/netapp-trident/TridentBackendConfig/coe-netapp-nas.yaml#L7C22-L7C31)
- [ontap-san-economy](https://github.com/stormshift/clusters/blob/main/configuration/overlays/isar/namespace/netapp-trident/TridentBackendConfig/coe-netapp-san.yaml#L7C23-L7C37)

**Comment by rbo** [comment]
Added missing VolumeSnapshotClass

**Comment by rbo** [comment]
New Default storage class ist coe-netapp-san (iscsi) with volume snapshot!
