### ISSUE TITLE
CNV: enable persistent uefi state

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#170]
See here:
https://kubevirt.io/user-guide/virtual_machines/persistent_tpm_and_uefi_state/

**Comment by DanielFroehlich** [comment]
Merged and synced.

**Comment by rbo** [comment]
ArgocD is not in sync what that change you made in https://github.com/stormshift/clusters/pull/13

**Comment by rbo** [comment]
https://openshift-gitops-server-openshift-gitops.apps.isar.coe.muc.redhat.com/applications/openshift-gitops/operator-ocp-v?view=tree&resource=sync%3AOutOfSync&node=hco.kubevirt.io%2FHyperConverged%2Fopenshift-cnv%2Fkubevirt-hyperconverged%2F0

**Comment by DanielFroehlich** [comment]
Fixed!
