### ISSUE TITLE
arista-rj45 - down

### ISSUE THREAD

**Issue by rbo** [stormshift/support#172]

**Comment by rbo** [comment]
Power unplug and plug doesn't help. LED's from all FANS are still red

**Comment by rbo** [comment]
Switch model: Arista Switch  DCS-7140T-8S
FAN: San Ace 40 / 9cra0412p4k08

**Comment by dmoessne** [comment]
We opened the switch, nothing obvious. 
Tests:
Cross changed PSU and fans
trying just one PSU
always same symptom: After plugging in power cords, the flans LEDs flicker shortly green before they switch to read. 
Switch not available at all

**Comment by rbo** [comment]
Replacement switch (10.32.104.13, DGS-3630-52TC, GigaBit) configuration in progress

**Comment by rbo** [comment]
New switch  arrived... let's configure it...

**Comment by rbo** [comment]
Switch replaced.
