### ISSUE TITLE
odr-hub operator is crashlooping

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#177]
https://console-openshift-console.apps.isar.coe.muc.redhat.com/k8s/ns/openshift-operators/deployments/ramen-hub-operator/pods
is crashlooping. I have seen OOMKills in action. 
@rbo , I see [no CR being instantiated currently.](https://console-openshift-console.apps.isar.coe.muc.redhat.com/k8s/ns/openshift-operators/operators.coreos.com~v1alpha1~ClusterServiceVersion/odr-hub-operator.v4.15.1-rhodf/instances) 

Okay if I remove this operator for now, as its seems to be unused?

**Comment by rbo** [comment]
Removed. Not needed at the moment.
