### ISSUE TITLE
Disable HyperThreading and enable nested virt on ISAR BM Nodes

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#178]
Currently, ISAR Bare Metal Nodes have Hyperthreading enabled.
Thats a bit dangerous, because we feel like "unlimited" CPU capacity with reported 448 vCPUs. But actually, system will become slower when 50% CPU utilisation is reached. Hyperthreading does not double the capacity. Best case only by a factor of 10-30%, depending on the workload. And maybe even not at all. Which means: a system that reports 50% utilisation is actually way more utilised then it looks like. And it starts to become slower. 

We are starting to see 50% utili on individual nodes of ISAR:
![image](https://github.com/stormshift/support/assets/18532443/673b51b3-572c-45c3-880f-4b928c96a8a6)
(e..g ucs57).

In stormshift RHV, I did disable Hyperthreading to avoid this pitfall and always have maximum performance. 

Lets discuss!

**Comment by rbo** [comment]
I will provide a machine config pool where we can disable hyperthreading via kernel arg. Then we can easily switch back and forth for testing purposes.

**Comment by rbo** [comment]
Let's create another machineconfig pool for virtualization with:
 * Disabled Hyperthreading https://access.redhat.com/solutions/6984039
 * Enabled Nested virt. https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/configuring_and_managing_virtualization/creating-nested-virtual-machines_configuring-and-managing-virtualization#creating-a-nested-virtual-machine-on-intel_creating-nested-virtual-machines

**Comment by rbo** [comment]
Works:
![Screenshot 2024-10-01 at 16 59 16](https://github.com/user-attachments/assets/d131b57b-1ee0-4077-8069-98f2880e70ec)

**Comment by rbo** [comment]
Done, all nodes in the virt-node mcp:
```
 oc get mcp
NAME           CONFIG                                                   UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
master         rendered-master-af3aabcf3f3d1cb565ef6ac7989d397f         True      False      False      3              3                   3                     0                      407d
storage-node   rendered-storage-node-d415a48b5bbcf0f0a609285ee67bb8fe   True      False      False      3              3                   3                     0                      86d
virt-node      rendered-virt-node-ea59fa4940a326eac346a611e2f0fb4c      True      False      False      7              7                   7                     0                      86d
worker         rendered-worker-51b8f524b960998d9909babbc8701b74         True      False      False      0              0                   0    
```
