### ISSUE TITLE
ISAR: Increase operator CatalogSource update interval

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#179]
CatalogSources are currently set to the default poll interval of 10 minutes. Thats creates a log of noise in the event logs. And feels kind of unnecessary. every 6 or 12 hours should be good enough. We dont need to be on latest&greatest bleeding edge of technology I think.

@rbo , wdyt? I could add this to the gitops config

**Comment by rbo** [comment]
Agree

**Comment by DanielFroehlich** [comment]
Turns out: field cant be overwritten, its owned by the Operator Hub and cant be customised:
https://access.redhat.com/solutions/7010772
Unless we disable the managed in OperatorHub and do it on our own. Which I think we should avoid to keep on up to date streams, esp. after upgrades.

@rbo  Or are you aware of other ways of changing it?

**Comment by DanielFroehlich** [comment]
As discussed, closing this as wont do until 
[RFE](https://issues.redhat.com/browse/RFE-5603
) is done.

**Comment by DanielFroehlich** [comment]
cant fix
