### ISSUE TITLE
ISAR ACM Obs: ACMThanosCompactBucketHighOperationFailures

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#182]
Alert:
Thanos Compact observability-thanos-compact in open-cluster-management-observability Bucket is failing to execute 100% of operations.

**Comment by DanielFroehlich** [comment]
% oc logs -f observability-thanos-compact-0      
ts=2024-06-11T09:28:09.87438218Z caller=compact.go:568 level=error msg="retriable error" err="syncing metas: BaseFetcher: iter bucket: Bucket name cannot be longer than 63 characters"

--> Something wrong with the bucket name. Funny, as this should be generated from ODF.
Checking the thanos object bucket claim and secret....

**Comment by DanielFroehlich** [comment]
Indeed, bucket name is "acm-observability-thanos-b-be621630-1393-4d25-aefe-d34ff1eda020" which is 64 chars long!
Bummer, need to re-deploy / change the object bucket to a shorter name.
Will do this after @rbo demos today.

**Comment by rbo** [comment]
@DanielFroehlich I‘m done well free to start

**Comment by DanielFroehlich** [comment]
Fixed!
