### ISSUE TITLE
Failed to run VMs for OCP4 cluster

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#186]
Failed to start VM from RHEV, e.g. ocp4bastion but also other nodes do not start.

**Comment by DanielFroehlich** [comment]
Very strange, simple error message:
![image](https://github.com/stormshift/support/assets/18532443/c25c7383-f096-4bc5-afe0-48d55277bb1a)
no more details.

**Comment by knumskull** [comment]
issue found - networks `ocp4-network` and `ocp6-odf` are not configured on any host - that's why the vms can't start.
undefine the network from the VM configuration will start the VMs. 
I don't know where those networks have to be configured from host point of view, so I can't fix it.

**Comment by DanielFroehlich** [comment]
@knumskull thx for the quick look! ocp4-network is a "virtual network" using the  ovirt-provider-ovn.  not a physicall one. it should be available on all nodes. its use to create a totally private network for all the ocp4... cluster VMs.

Its showing as operational in the cluster:
![image](https://github.com/stormshift/support/assets/18532443/31758cad-2b64-4d9c-beea-5282bf3eade9)
Any ideas on how to revive that?

**Comment by knumskull** [comment]
Good point. Probably ovn is causing some trouble. Will investigate into that direction.

**Comment by knumskull** [comment]
It might be related to a certificate issue

```
[root@rhev ~]# openssl verify -CAfile /etc/pki/ovirt-engine/apache-ca.pem /etc/pki/ovirt-engine/certs/apache.cer
O = Red Hat, OU = prod, CN = 2023 Certificate Authority RHCSv2
error 2 at 1 depth lookup: unable to get issuer certificate
error /etc/pki/ovirt-engine/certs/apache.cer: verification failed
```

Are all CA and intermediate CA included in `/etc/pki/ovirt-engine/apache-ca.pem` ?

**Comment by DanielFroehlich** [comment]
Ah! Good catch! By bad - we got new certs earlier this year, which are create by a new Red Hat Internal CA certificate.
Looks like I added the wrong certs to the apache-ca file, that is not the cert chain, but the server cert itself:
```
openssl x509 -in apache-ca.pem -noout -dates -subject
notBefore=Jan  2 16:42:32 2024 GMT
notAfter=Dec 27 16:42:32 2024 GMT
subject=O = Red Hat, OU = SolutionArchitectsDach, CN = *.stormshift.coe.muc.redhat.com

```

I dropped  the correct root ca chain to `/root/2023CertificateAuthorityRHCSv2_Chain.pem` on the rhev host. With that, the verify checks out:
```
[root@rhev ovirt-engine]#  openssl verify -CAfile /root/2023CertificateAuthorityRHCSv2_Chain.pem /etc/pki/ovirt-engine/certs/apache.cer
/etc/pki/ovirt-engine/certs/apache.cer: OK

```

Can I simply replace the apache-ca.pem or does this require a special procedure?

**Comment by knumskull** [comment]
It might be sufficient to replace the apache-ca with a following restart of engine and ovirt-provider-ovn.

But I can check in a couple of minutes again and follow up.

**Comment by knumskull** [comment]
I replaced the ca-certificate the system in question is up and running again.
![image](https://github.com/stormshift/support/assets/2650167/1e6bbfcd-77ce-435f-a967-7e9e95481aa1)

Due to other changes, I had to re-create the OVN networks and they show now MTU1500 in UI. This is only a display issue in the UI. They're operating at 1442 inside the VMs.

**Comment by DanielFroehlich** [comment]
Thx! I started the remaining VMs, too. They are all up and running now.

@Javatar81 , the cluster is now suffering from expired certs. I did approve all pending CSR, cluster should recover now. Please check again in an hour or so. This issue is resolved, I am closing it.

**Comment by Javatar81** [comment]
Thanks all for your great support. Had to approve still some missing CSRs but now the cluster is healthy and I will update soon once the cluster fully recovered
