### ISSUE TITLE
OCP3 high CPU consumption

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#28]
Cant log in to OCP3, just get a 
"{"error":"server_error","error_description":"The authorization server encountered an unexpected condition that prevented it from fulfilling the request.","state":"a8196c45"}"  in the browser after login.

RHEV console shows high CPU consumption:
![image](https://user-images.githubusercontent.com/18532443/133490098-b1808ffa-4514-45c3-a677-a7a2abcd66ba.png)

**Comment by DanielFroehlich** [comment]
@ortwinschneider , would you mind taking a look?

**Comment by sdcloudy** [comment]
rebooting environment at 17:15 CEST with wmarx

**Comment by sdcloudy** [comment]
we have rebooted the compute and control nodes, however there seems to be no network connectivity and in rhv there are no errors showing up in the events.
link state is up, not sure how to troubleshoot further as we can't access the VM hosts console right now.

**Comment by DanielFroehlich** [comment]
seems to work now. closing issue!
