### ISSUE TITLE
OCP4 - pods with frequent restarts

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#29]
I see a lot of pods with >10.000 restarts, around codeready workspaces, knative eventing:
https://console-openshift-console.apps.ocp4.stormshift.coe.muc.redhat.com/k8s/all-namespaces/pods?orderBy=desc&sortBy=Restarts
This creates unnessary CPU load.
Check it out here:
https://console-openshift-console.apps.ocp4.stormshift.coe.muc.redhat.com/k8s/all-namespaces/pods?orderBy=desc&sortBy=Restarts
![image](https://user-images.githubusercontent.com/18532443/133493507-fc6e375c-c6fe-4fbc-bbb7-850df43ed0dd.png)

**Comment by DanielFroehlich** [comment]
@Javatar81 , would you mind taking a look and work with the owners to fix? Thx Daniel

**Comment by Javatar81** [comment]
Cleaned up
