### ISSUE TITLE
Trigger problems in several BuildConfigs

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#38]
Example: `error triggering Build for BuildConfig default/cakephp-mysql-example: Internal error occurred: build config default/cakephp-mysql-example has already instantiated a build for imageid image-registry.openshift-image-registry.svc:5000/openshift/php@sha256:bbb9469731881762ab999ff8871378fc2852a11d7e5ad897e142bddde77f7b96`

**Comment by DanielFroehlich** [comment]
please dont use the "default" namespace
