### ISSUE TITLE
move automation/doc into own repo

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#4]
robert and daniel agreed on name for new repo: "documentation"

**Comment by rbo** [comment]
Worklog:
```
git clone git@github.com:stormshift/automation.git documentation && cd documentation/

**Comment by rbo** [comment]
@DanielFroehlich please verify the documentation repo: https://github.com/stormshift/documentation - from my point of view it looks good enough. Now we have to update the documentation.

**Comment by rbo** [comment]
Close looks fine.
