### ISSUE TITLE
Install plan in openshift-operators requires manual update of all operators

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#6]
Although I just want to confirm installation of OpenShift Pipelines, I need to confirm all other operators in the same namespace:

- amq-online.1.7.0
- gpu-operator-certified.v1.5.2
- opendatahub-operator.v1.0.10
- redhat-openshift-pipelines.v1.4.1

**Comment by DanielFroehlich** [comment]
closing as stale issue, as nobody took care of it for ~6 months. Also, not sure if this is a stormshift issue or a general OCP OLM topic
