### ISSUE TITLE
Please update RHV at least to 4.4.5 or later

### ISSUE THREAD

**Issue by rbo** [stormshift/support#63]
OpenShift IPI failed because of old RHV version:
```
E0107 13:56:59.291549       1 actuator.go:180] machine ocp2-zhsnd-worker-q8lts error: error validating machine fields: error validating AutoPinningPolicy: the engine version 4.4.3 is not supporting the auto pinning feature. Please update to 4.4.5 or later
``` 

Please update RHV at least to 4.4.5 or later

**Comment by mschindl** [comment]
Workaround: 

> [root@stormshiftdeploy stormshift]# export KUBECONFIG=/root/ocp2_install/auth/kubeconfig 
> [root@stormshiftdeploy stormshift]# oc get nodes
> NAME                  STATUS   ROLES    AGE   VERSION
> ocp2-6598l-master-0   Ready    master   53m   v1.22.3+ffbb954
> ocp2-6598l-master-1   Ready    master   53m   v1.22.3+ffbb954
> ocp2-6598l-master-2   Ready    master   55m   v1.22.3+ffbb954
> [root@stormshiftdeploy stormshift]# oc get machineset -n openshift-machine-api
> NAME                DESIRED   CURRENT   READY   AVAILABLE   AGE
> ocp2-6598l-worker   2         2                             57m
> [root@stormshiftdeploy stormshift]# oc edit -n openshift-machine-api machineset ocp2-6598l-worker
> machineset.machine.openshift.io/ocp2-6598l-worker edited

Remove line: auto_pinning_policy

> [root@stormshiftdeploy stormshift]# oc scale -n openshift-machine-api machineset ocp2-6598l-worker --replicas=0
> machineset.machine.openshift.io/ocp2-6598l-worker scaled
> [root@stormshiftdeploy stormshift]# oc scale -n openshift-machine-api machineset ocp2-6598l-worker --replicas=3
> machineset.machine.openshift.io/ocp2-6598l-worker scaled

Check status:

```
Every 2.0s: oc get nodes,machines -n openshift-machine-api                                          stormshiftdeploy.coe.muc.redhat.com: Mon Jan 17 13:29:26 2022

NAME                       STATUS   ROLES    AGE   VERSION
node/ocp2-6598l-master-0   Ready    master   57m   v1.22.3+ffbb954
node/ocp2-6598l-master-1   Ready    master   57m   v1.22.3+ffbb954
node/ocp2-6598l-master-2   Ready    master   59m   v1.22.3+ffbb954

NAME                                                   PHASE          TYPE   REGION   ZONE   AGE
machine.machine.openshift.io/ocp2-6598l-master-0       Running                               59m
machine.machine.openshift.io/ocp2-6598l-master-1       Running                               59m
machine.machine.openshift.io/ocp2-6598l-master-2       Running                               59m
machine.machine.openshift.io/ocp2-6598l-worker-c2zsl   Provisioning                          77s
machine.machine.openshift.io/ocp2-6598l-worker-rtpc7   Provisioning                          77s
machine.machine.openshift.io/ocp2-6598l-worker-xq9xb   Provisioning                          77s
```

**Comment by DanielFroehlich** [comment]
Done!
RHEV now on V4.4.9.5-0.1.el8ev
