### ISSUE TITLE
Onboarding cluster/ocp3

### ISSUE THREAD

**Issue by rbo** [stormshift/support#7]
- [x] Setup a Admin-Team 
- [x] Adjust notfication workflow
- [x] Add label

**Comment by rbo** [comment]
@DanielFroehlich who is responsible for cluster/ocp3? Please provide github account name.

**Comment by DanielFroehlich** [comment]
@ortwinschneider, already invited and added to the team.

**Comment by rbo** [comment]
Awesome, I adjusted the notification workflow.
