### ISSUE TITLE
OCP4 NotReady after COE Lab re-build

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#78]
OCP4 Cluster is in INOP state after rebuild, login not working etc.
Looks like we have lost quorum, too many not ready nodes:
```
[root@ocp4bastion ~]# oc get nodes
NAME                                           STATUS     ROLES    AGE     VERSION
compute-0.ocp4.stormshift.coe.muc.redhat.com   Ready      worker   2y86d   v1.21.6+4b61f94
compute-1.ocp4.stormshift.coe.muc.redhat.com   NotReady   worker   2y86d   v1.21.6+4b61f94
compute-2.ocp4.stormshift.coe.muc.redhat.com   Ready      worker   550d    v1.21.6+4b61f94
control-0.ocp4.stormshift.coe.muc.redhat.com   Ready      master   2y86d   v1.21.6+4b61f94
control-1.ocp4.stormshift.coe.muc.redhat.com   NotReady   master   2y86d   v1.21.6+4b61f94
control-2.ocp4.stormshift.coe.muc.redhat.com   NotReady   master   2y86d   v1.21.6+4b61f94
gpu.ocp4.stormshift.coe.muc.redhat.com         Ready      worker   157d    v1.21.6+4b61f94
```
I suspect cert issue due to long days offline. I did approve CSR in state pending, but that did not help.
We need to invistigate and probably recover from expirired certs. We had this issue already, please search here for the resulotion.

**Comment by DanielFroehlich** [comment]
@Javatar81 would you be able to take a look?

**Comment by DanielFroehlich** [comment]
Please check if it is the same as https://github.com/stormshift/support/issues/46

**Comment by DanielFroehlich** [comment]
control-1 (NotReady):
```
[core@control-1 ~]$  systemctl status kubelet
Apr 13 09:38:33 control-1.ocp4.stormshift.coe.muc.redhat.com hyperkube[126009]: I0413 09:38:33.812969  126009 csi_plugin.go:1031] Failed to contact API server when waiting for CSINode publishing: csinodes.storage.k8s.io "control-1.ocp4.stormshift.coe.muc.redhat.com" is forbidden: User "system:anonymous" cannot get resource "csinodes" in API g>
Apr 13 09:38:33 control-1.ocp4.stormshift.coe.muc.redhat.com hyperkube[126009]: E0413 09:38:33.907551  126009 kubelet.go:2303] "Error getting node" err="node \"control-1.ocp4.stormshift.coe.muc.redhat.com\" not found"
````

**Comment by Javatar81** [comment]
Identified problem with Kubelets not working. Followed these docs [](https://docs.openshift.com/container-platform/4.8/support/troubleshooting/verifying-node-health.html#querying-kubelet-status-on-a-node_verifying-node-health)

`systemctl status kubelet`
`found kubelet.go:2303] "Error getting node" err="node \"[control-1.ocp4.stormshift.coe.muc.redhat.com](http://control-1.ocp4.stormshift.coe.muc.redhat.com/)\" not found"`

Recovering as described in this issue: https://github.com/stormshift/support/issues/72

- Control-1
- Control-2
- Compute-1

Approved CSRs and enabled scheduling

**Comment by Javatar81** [comment]
All nodes are ready

**Comment by DanielFroehlich** [comment]
LGTM, THX
