### ISSUE TITLE
OpenShift Pipelines does not work after reinstalling

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#8]
When navigating to the Pipelines section of the navigation:

Error Loading Cluster Tasks: conversion webhook for tekton.dev/v1alpha1, Kind=ClusterTask failed: Post "https://tekton-pipelines-webhook.openshift-pipelines.svc:443/?timeout=30s": dial tcp 10.129.0.21:8443: connect: connection refused

**Comment by Javatar81** [comment]
Removed CRD as described in the docs. Now I cannot even install the operator: https://console-openshift-console.apps.ocp4.stormshift.coe.muc.redhat.com/k8s/ns/openshift-operators/operators.coreos.com~v1alpha1~Subscription/openshift-pipelines-operator-rh/yaml

**Comment by DanielFroehlich** [comment]
closing as stale issue
