### ISSUE TITLE
Storm3 is down

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#82]

**Comment by DanielFroehlich** [comment]
storm6 also, was again the watchdog issue:
![image](https://user-images.githubusercontent.com/18532443/164248592-5016390e-2f69-4e00-83c6-184cd51007ed.png)

**Comment by DanielFroehlich** [comment]
storm3 log last messages bevor reboot:
```
Apr 19 16:15:50 storm3 sanlock[2063]: 2022-04-19 16:15:50 251755 [2063]: s1 kill 570915 sig 15 count 26
Apr 19 16:15:51 storm3 wdmd[2062]: test failed rem 20 now 251755 ping 251705 close 251715 renewal 251650 expire 251730 client 2063 sanlock_2
4aaade7-ee5a-49a4-8220-5dbb4f71f8aa:1
Apr 19 16:15:51 storm3 named[2570]: resolver priming query complete
Apr 19 16:15:51 storm3 sanlock[2063]: 2022-04-19 16:15:51 251756 [2063]: s1 kill 570915 sig 15 count 27
Apr 19 16:15:52 storm3 wdmd[2062]: test failed rem 19 now 251756 ping 251705 close 251715 renewal 251650 expire 251730 client 2063 sanlock_2
4aaade7-ee5a-49a4-8220-5dbb4f71f8aa:1
Apr 19 16:15:52 storm3 sanlock[2063]: 2022-04-19 16:15:52 251757 [2063]: s1 kill 570915 sig 15 count 28
Apr 19 16:15:53 storm3 wdmd[2062]: test failed rem 18 now 251757 ping 251705 close 251715 renewal 251650 expire 251730 client 2063 sanlock_2
4aaade7-ee5a-49a4-8220-5dbb4f71f8aa:1
Apr 19 16:15:53 storm3 vdsm[4420]: WARN executor state: count=5 workers={<Worker name=qgapoller/1 waiting task#=12582 at 0x7fd6f904d400>, <W
orker name=qgapoller/0 waiting task#=12582 at 0x7fd6f903c860>, <Worker name=qgapoller/2 running <Task discardable <Operation action=<bound m
ethod QemuGuestAgentPoller._poller of <vdsm.virt.qemuguestagent.QemuGuestAgentPoller object at 0x7fd6f904dcc0>> at 0x7fd6f903c550> timeout=3
0, duration=30.00 at 0x7fd6faf20358> discarded task#=12581 at 0x7fd6f905e470>, <Worker name=qgapoller/3 waiting task#=12581 at 0x7fd6f905e51
8>, <Worker name=qgapoller/4 waiting task#=0 at 0x7fd6f84f8da0>}
Apr 19 16:15:53 storm3 sanlock[2063]: 2022-04-19 16:15:53 251758 [2063]: s1 kill 570915 sig 15 count 29
Apr 19 16:15:54 storm3 wdmd[2062]: test failed rem 17 now 251758 ping 251705 close 251715 renewal 251650 expire 251730 client 2063 sanlock_24aaade7-ee5a-49a4-8220-5dbb4f71f8aa:1

```

**Comment by DanielFroehlich** [comment]
both storm3 and 6 rebooted, RHEV is back online. Keeping this issue open to monitor it.

On storm6, I did change the BIOS setting regarding the Watchdog timer:
It was:
![image](https://user-images.githubusercontent.com/18532443/164248929-8a135312-f3a2-4bf2-918c-cfa477f777cd.png)

Now it is ENABLED - let's see if this changes something.

**Comment by DanielFroehlich** [comment]
Did happen today again, both storm3 +6 affected.
changing the watchdog setting in bios did not help, the system now really just freezes. what I think is trange that storm3 and storm6 do this kind of simultaneously. I will set rhev engine on storm3 in local maintenance mode, lets see if this helps. 
`[root@storm3 ~]# hosted-engine --set-maintenance --mode=local
`

**Comment by rbo** [comment]
Storm3 is down again, storm 6 is running. 
Memtest is running on storm3 
![image](https://user-images.githubusercontent.com/36604/165336148-615733dd-8967-4f19-8030-d2996cf81ce1.png)

**Comment by rbo** [comment]
![image](https://user-images.githubusercontent.com/36604/166214162-ef57e48a-79b0-4799-b445-27bc0f27337b.png)
Memtest looks good.

**Comment by rbo** [comment]
Reboot into RHEV

**Comment by DanielFroehlich** [comment]
Just saw a note regrading Bios:
https://www.reddit.com/r/vmware/comments/udodo0/avoid_dell_bios_2140_on_r730/
![image](https://user-images.githubusercontent.com/18532443/174651537-830389bd-d497-4b60-a403-3932f6b70e7c.png)


"dsu"- command line actually shows that downgrade. Executing it now:
![image](https://user-images.githubusercontent.com/18532443/174651632-2e8dfc1e-3eca-4e6d-87cd-ff731c906878.png)

Lets see if this helps

**Comment by DanielFroehlich** [comment]
downgraded storm6 today, too (pending reboot) as it hung up yesterday evening.
but storm3 maybe had another hang yesterday evening, too (Steffen reported a hung and did IDRac reboot)

**Comment by DanielFroehlich** [comment]
had a storm2 hangup on Jul/2, which got fixed by fence agent reboot.
BIOD downgrade to storm2  and storm5 today.
So all hypervisors are now downgraded to BIOS 2.13.0.

**Comment by DanielFroehlich** [comment]
looks like the bios downgrade did fix the issue - we had no hangup / freeze since then. Closing this issue now.
