### ISSUE TITLE
Postinstall does not configure SSO properly 

### ISSUE THREAD

**Issue by mschindl** [stormshift/support#84]
Postinstall does not configure SSO properly 

Release: 4.9.31

SSO Login is missing:
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/26382876/168572470-7c46b5d7-a6b4-4b9b-b4b6-47bd3b9c074e.png">

- [X] https://source.redhat.com/groups/public/solution-architects/stormshift/stormshift_wiki/install_openshift_v4_cluster_using_rhv_ipi

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/26382876/168572970-c4ee4f30-aeb1-415a-b422-c33f1baa94e7.png">

- Cluster
https://console-openshift-console.apps.ocp2.stormshift.coe.muc.redhat.com/dashboards

**Comment by DanielFroehlich** [comment]
It takes a while to take effect. Looks good to me know, I did not change anything:
![image](https://user-images.githubusercontent.com/18532443/168755962-9909637e-6c31-4683-810b-057df20a62de.png)

**Comment by rbo** [comment]
Just for information, usually the authentication cluster operator is in progress during the configuration role-out and yes this can take some time.
