### ISSUE TITLE
Power outage 2022-06-04

### ISSUE THREAD

**Issue by rbo** [stormshift/support#86]
Power-input 

1. 1x 25A via USV ~ 5750 Watt 
2. 3x 16A direct ~ 3680 Watt each

**Comment by rbo** [comment]
Tomowwor I will change power from USV to non USV of server:
- [x] inf45
- [x] inf49
- [x] storm2
- [ ] storm3
- [x] storm1

**Comment by rbo** [comment]
Power of inf45, usv load is at 80%

**Comment by DanielFroehlich** [comment]
Can we keep Storm 3 on usv? NFS and DNS is running there. Storm 4,5 would be better if on USV to move to non USV

**Comment by rbo** [comment]
Per rack we have 2x 16 A

----

- Storm 1, PSU 3 & 4 => Direct A, PSU 1 & 2 => direct B
- Inf46 1x Direct A, 1x Direct B
- Storm 2, 1x Direct A, 1x Direct B
- Direct C -> UCS Blade & Fabric interconnect
- Direct D -> All SF 1-4 
- Storm 4 2x Direct E
- Storm 5 2x Direct E
- Storm 6 1x Direct E , 1x Direct F

**Comment by rbo** [comment]
- Inf47 direct F

**Comment by rbo** [comment]
- Inf49 direct F

**Comment by rbo** [comment]
- inf45 direct A&B

**Comment by rbo** [comment]
![image](https://user-images.githubusercontent.com/36604/172864787-bd8f3644-4f14-4496-888f-a7fa925fc45f.png)

DONE :-)
