### ISSUE TITLE
Reinstall inf31 - Monitoring & Secondary IDP

### ISSUE THREAD

**Issue by rbo** [stormshift/support#93]
- [x] Reinstall inf32 with RHEL8
- [x] Added permanent KVM / avocent 
- [x] Check network cable - if should be connected to the cisco switch
- [x] Install OMD https://labs.consol.de/omd/ - https://inf31.coe.muc.redhat.com/mon
   - [ ] Configure basic checks
     - [ ] Ping check mgmt interface
     - [ ] Ping check primary interface
     - [ ] SSH Login?
   - [x] Alerting into Telegram group
   - [x] Room Temperature  checks  

/cc @astolzen @dmoessne

**Comment by DanielFroehlich** [comment]
Good Action! Can we please alert to Gchat? Or email?

**Comment by rbo** [comment]
@DanielFroehlich of course, we can configure different alerts to email or gchat for different servers, checks, groups whatever...

**Comment by rbo** [comment]
RHEL 8 removed the driver of the raid controller:

![image](https://user-images.githubusercontent.com/36604/178211182-b9cf7541-a878-4c3f-b4e2-9228dae2e337.png)

**Comment by rbo** [comment]
Tried to add the driver during [https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_an_advanced_rhel_8_installation/index#updat[…]d-user](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_an_advanced_rhel_8_installation/index#updating-drivers-during-installation_installing-rhel-as-an-experienced-user)  with ISO https://elrepo.org/linux/dud/el8/x86_64/dd-aacraid-1.2.1-7.el8_6.elrepo.iso

Did not work.


I ordered a cheap NVME PCIE for operating system. Then we can easily install customer kernel modules for the raid controller after OS installation and use the disks for pure Data.

**Comment by rbo** [comment]
OMD installed: https://inf31.coe.muc.redhat.com/mon 

Scondary IDP installed: https://github.com/stormshift/support/issues/99

**Comment by DanielFroehlich** [comment]
Can we add a nice cert? The stormshift master cert has a SAN of "monitor.stormshift.coe.muc.redhat.com" - if we add this as vhost to thruk (alaias to inf31) and provide a DNS entry, it would work. What do you think?

**Comment by rbo** [comment]
> Can we add a nice cert? The stormshift master cert has a SAN of "monitor.stormshift.coe.muc.redhat.com" - if we add this as vhost to thruk (alaias to inf31) and provide a DNS entry, it would work. What do you think?

Technical possible, to be honest: I try to avoid more effort and complexity.  A proper Red Hat certificate for inf31.coe.muc.redhat.com is on my To-Do list. Maybe you can assist to request an *.coe.muc.redhat.com certificate, then we can use this for much more "core" services?

**Comment by DanielFroehlich** [comment]
Here's ansible magic, I think only the last step using the PKI command is not working anymore, you have to upload the CSR manually to the Red Hat CA site:

https://github.com/stormshift/automation/blob/a9d319120c81d4e7ed5b93e6970863543e9eafa1/050_prepare_installhost.yml#L94

**Comment by rbo** [comment]
Setup is good enough :-)
